# Generated by Django 3.0.4 on 2020-03-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacient_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Subdivision',
            new_name='subdivision',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='FullName',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='WorkingСonditions',
            new_name='working_conditions',
        ),
        migrations.RenameField(
            model_name='patientcard',
            old_name='patient',
            new_name='title',
        ),
    ]
