# Generated by Django 3.0.4 on 2020-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient_queue', '0002_auto_20200309_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patientcard',
            name='vaccinations',
            field=models.ManyToManyField(to='pacient_queue.Vacinations'),
        ),
    ]
